---
1: !ruby/object:ItemYml
  name: Banana
  cost: '10'
2: !ruby/object:ItemYml
  name: Apple
  cost: '8'
3: !ruby/object:ItemYml
  name: Mandarin
  cost: '7'
4: !ruby/object:ItemYml
  name: Carrot
  cost: '5'
5: !ruby/object:ItemYml
  name: Staff
  cost: '120'
6: !ruby/object:ItemYml
  name: Sword
  cost: '78'
7: !ruby/object:ItemYml
  name: Katana
  cost: '88'
8: !ruby/object:ItemYml
  name: Wand
  cost: '123'
9: !ruby/object:ItemYml
  name: Spear
  cost: '66'
10: !ruby/object:ItemYml
  name: Cloak
  cost: '65'
11: !ruby/object:ItemYml
  name: Pants
  cost: '56'
12: !ruby/object:ItemYml
  name: Dagger
  cost: '45'
13: !ruby/object:ItemYml
  name: Hat
  cost: '34'
14: !ruby/object:ItemYml
  name: Belt
  cost: '22'
15: !ruby/object:ItemYml
  name: Helmet
  cost: '39'
16: !ruby/object:ItemYml
  name: Amulet
  cost: '145'
17: !ruby/object:ItemYml
  name: Ring
  cost: '98'
18: !ruby/object:ItemYml
  name: Boots
  cost: '19'
19: !ruby/object:ItemYml
  name: Bow
  cost: '100'
20: !ruby/object:ItemYml
  name: Earrings
  cost: '244'
