---
1: !ruby/object:ItemYml
  name: Банан
  cost: '10'
2: !ruby/object:ItemYml
  name: Яблоко
  cost: '8'
3: !ruby/object:ItemYml
  name: Мандарин
  cost: '7'
4: !ruby/object:ItemYml
  name: Морковь
  cost: '5'
5: !ruby/object:ItemYml
  name: Посох
  cost: '120'
6: !ruby/object:ItemYml
  name: Меч
  cost: '78'
7: !ruby/object:ItemYml
  name: Катана
  cost: '88'
8: !ruby/object:ItemYml
  name: Жезл
  cost: '123'
9: !ruby/object:ItemYml
  name: Глобус
  cost: '66'
10: !ruby/object:ItemYml
  name: Плащ
  cost: '65'
11: !ruby/object:ItemYml
  name: Штаны
  cost: '56'
12: !ruby/object:ItemYml
  name: Кинжал
  cost: '45'
13: !ruby/object:ItemYml
  name: Шляпа
  cost: '34'
14: !ruby/object:ItemYml
  name: Каска
  cost: '22'
15: !ruby/object:ItemYml
  name: Шлем
  cost: '39'
16: !ruby/object:ItemYml
  name: Амулет
  cost: '145'
17: !ruby/object:ItemYml
  name: Кольцо
  cost: '98'
18: !ruby/object:ItemYml
  name: Сапоги
  cost: '19'
19: !ruby/object:ItemYml
  name: Лук
  cost: '100'
20: !ruby/object:ItemYml
  name: Серьги
  cost: '244'
