---
1: !ruby/object:Item
  name: Банан
  cost: '10'
  id: 1
2: !ruby/object:Item
  name: Яблоко
  cost: '8'
  id: 2
3: !ruby/object:Item
  name: Мандарин
  cost: '7'
  id: 3
4: !ruby/object:Item
  name: Морковь
  cost: '5'
  id: 4
5: !ruby/object:Item
  name: Посох
  cost: '120'
  id: 5
6: !ruby/object:Item
  name: Меч
  cost: '78'
  id: 6
7: !ruby/object:Item
  name: Катана
  cost: '88'
  id: 7
8: !ruby/object:Item
  name: Жезл
  cost: '123'
  id: 8
9: !ruby/object:Item
  name: Глобус
  cost: '66'
  id: 9
10: !ruby/object:Item
  name: Плащ
  cost: '65'
  id: 10
11: !ruby/object:Item
  name: Штаны
  cost: '56'
  id: 11
12: !ruby/object:Item
  name: Кинжал
  cost: '45'
  id: 12
13: !ruby/object:Item
  name: Шляпа
  cost: '34'
  id: 13
14: !ruby/object:Item
  name: Каска
  cost: '22'
  id: 14
15: !ruby/object:Item
  name: Шлем
  cost: '39'
  id: 15
16: !ruby/object:Item
  name: Амулет
  cost: '145'
  id: 16
17: !ruby/object:Item
  name: Кольцо
  cost: '98'
  id: 17
18: !ruby/object:Item
  name: Сапоги
  cost: '19'
  id: 18
19: !ruby/object:Item
  name: Лук
  cost: '100'
  id: 19
20: !ruby/object:Item
  name: Серьги
  cost: '244'
  id: 20
